export const CMDB_ROUTE = '/cmdb'
export const DASHBOARD_ROUTE = '/dashboard'
export const NETWORK_ROUTE = '/network'
export const PRINTERS_ROUTE = '/printers'
export const HYPERVISORS_ROUTE = '/hypervisors'
export const NETWORK_DEVICES_ROUTE = '/network-devices'